package practica2;

import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jorge
 */
public class Saluditos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Saluditos() {

        initComponents();
        setLocationRelativeTo(null); // Centrar en la pantalla

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mano = new javax.swing.JLabel();
        Texto_Comunicacion = new javax.swing.JLabel();
        Boton_Confirma_Saludo = new javax.swing.JButton();
        Introducir_nombre_completo = new javax.swing.JTextField();
        Imagen_mano = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saludo_al_usuario");

        Mano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica2/pkg2/media/saluda.png"))); // NOI18N

        Texto_Comunicacion.setText("Escribe el nombre del usuario:");

        Boton_Confirma_Saludo.setText("Saludo");
        Boton_Confirma_Saludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Confirma_SaludoActionPerformed(evt);
            }
        });

        Introducir_nombre_completo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Introducir_nombre_completoActionPerformed(evt);
            }
        });

        Imagen_mano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/saluda.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(Imagen_mano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mano)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Texto_Comunicacion)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Boton_Confirma_Saludo)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Introducir_nombre_completo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Mano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(Imagen_mano)
                        .addGap(18, 18, 18)))
                .addComponent(Texto_Comunicacion)
                .addGap(18, 18, 18)
                .addComponent(Introducir_nombre_completo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Boton_Confirma_Saludo)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Boton_Confirma_SaludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Confirma_SaludoActionPerformed
        String nombreCompleto = Introducir_nombre_completo.getText().trim();

        // Validaciones
        if (nombreCompleto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena el campo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nombreCompleto.split(" ").length < 2) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce al menos un nombre y un apellido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nombreCompleto.length() < 5) {
            JOptionPane.showMessageDialog(this, "El nombre y apellidos deben tener al menos 5 caracteres en total.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!nombreCompleto.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ //s]+")) {
            // Mensaje de error si hay números o símbolos
            JOptionPane.showMessageDialog(this, "El nombre no debe contener números ni símbolos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Si las validaciones son correctas, mostrar el saludo
        JOptionPane.showMessageDialog(this, "Hola " + nombreCompleto + "!", "Saludo", JOptionPane.INFORMATION_MESSAGE);

        // Borrar el campo de texto
        Introducir_nombre_completo.setText("");

    }//GEN-LAST:event_Boton_Confirma_SaludoActionPerformed

    
    private void Introducir_nombre_completoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Introducir_nombre_completoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Introducir_nombre_completoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saluditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saluditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saluditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saluditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saluditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Confirma_Saludo;
    private javax.swing.JLabel Imagen_mano;
    private javax.swing.JTextField Introducir_nombre_completo;
    private javax.swing.JLabel Mano;
    private javax.swing.JLabel Texto_Comunicacion;
    // End of variables declaration//GEN-END:variables
}
